version: "3.7"
services:
  postgres:
    image: postgres:10.3-alpine
    volumes:
      - ./database/data:/var/lib/postgresql/data/pgdata:rw
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "America/Santiago"

  keycloak:
    #image: jboss/keycloak
    build:
      context: ./
      dockerfile: docker/keycloak/Dockerfile
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_SCHEMA: public
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
    - 8080:8080
    - 8443:8443
    - 9990:9990
    depends_on:
    - postgres

  rest-sample:
    build:
      context: ./rest-sample/
      dockerfile: Dockerfile
    ports:
    - 8081:8080
